### ISSUE TITLE
Link is invalid

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [eclipse-4diac/4diac-fbe#12]
Hi, 

https://github.com/eclipse-4diac/4diac-toolchain/tree/e7f0c89744ee56ee37be70f5376e1d4a4a27a2c3
this link is in the current "Develop" of https://github.com/eclipse-4diac/4diac-fbe but it cannot be accessed. 

seems like https://github.com/eclipse-4diac/4diac-toolchain was not pushed.

**Comment by azoitl** [comment]
Can you please explain more what the problem is. For me FBE in its current form works well. So it would be good to explain the error you are experiencing.

**Comment by jwalt** [comment]
FBE links multiple different repos, therefore on the develop branch broken subrepo links can happen occasionally. The release branch is supposed to always work, you should use this preferably. If you absolutely want to run develop, manually use the develop branch of the toolchains subrepo. They usually match.

**Comment by diplfranzhoepfinger** [comment]
> Can you please explain more what the problem is. For me FBE in its current form works well. So it would be good to explain the error you are experiencing.

see here:

#13

**Comment by azoitl** [comment]
@diplfranzhoepfinger have you seen my response to #13?

**Comment by diplfranzhoepfinger** [comment]
![image](https://github.com/eclipse-4diac/4diac-fbe/assets/37779037/9d9d04d6-e7d8-45e4-975d-9aa3db624c38)
link is there, will test develop branch now.

**Comment by diplfranzhoepfinger** [comment]
develop branch still same error, i will report in #13
