### ISSUE TITLE
Errornous space in "develop" branch

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [eclipse-4diac/4diac-fbe#14]
I make here another issue for the develop branch,  
otherwise it might be forgotten.

we discuss release branch here: #13

develop:

we get this:

*   in Windows:
    *   [https://gist.github.com/diplfranzhoepfinger/4fbd342554ec4f9fa7278c5e89c2b72f](https://gist.github.com/diplfranzhoepfinger/4fbd342554ec4f9fa7278c5e89c2b72f)
*   in Linux:
    *   [https://gist.github.com/diplfranzhoepfinger/4e55b6bb8a42977d76b6745073c53870](https://gist.github.com/diplfranzhoepfinger/4e55b6bb8a42977d76b6745073c53870)

both cases same Message: `cp: unrecognized option: n` 

seems a additional space between `--` and `n` is causing this. 
while `--n` would be correct.

**Comment by jwalt** [comment]
This will be fixed in the next release that I am preparing right now. There was some overlap during my work on macos support that temprarily removed support for the `-n` flag.

**Comment by diplfranzhoepfinger** [comment]
> This will be fixed in the next release that I am preparing right now. There was some overlap during my work on macos support that temprarily removed support for the `-n` flag.

now it makes sense !
